# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(default='sms', max_length=3)),
                ('msg_getter', models.CharField(max_length=20)),
                ('msg_sender', models.CharField(default='01029953874', max_length=20)),
                ('msg_text', models.TextField()),
            ],
        ),
    ]
